### ISSUE TITLE
looking for dataset

### ISSUE THREAD

**Issue by gopalmenon** [HenryDev/MLND-P5-DiDi-Chuxing-Algorithm-Competition#1]
I could not find a way to download the train and test data from the Didi website. I realize the competition is over, but was interested in working on the problem. Do you have the data any place that I could get access to? Thanks!!!

**Comment by HenryDev** [comment]
you could try the link in this thread: https://discussions.udacity.com/t/download-citydata-tar-gz-very-slow/169169

or here: https://github.com/DonatasZiaukas/DiDi/tree/master/data/season_2/training_data

**Comment by gopalmenon** [comment]
Thanks!!!
